version: '3.9'

services:
  db:
    container_name: mssql
    image: mssql
    restart: always
    ports:
      - 8001:1433
    environment:
      ACCEPT_EULA: 1 
      MSSQL_USER: sa
      MSSQL_SA_PASSWORD: MyPass@word
      MSSQL_PID: Developer    

  api:
    container_name: webapi
    image: webapi
    restart: always
    depends_on: 
      - db
    ports:
       - 8000:80