version: '3.1'

services:

  mssql:
    container_name: mssql
    image: mssql
    restart: always
    environment:
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 1 
      MSSQL_USER: sa
      MSSQL_SA_PASSWORD: MyPass@word
      MSSQL_PID: Developer    

  webapi:
    container_name: webapi
    image: webapi
    restart: always
    depends_on: 
      - mssql
    ports:
       - 8081:80